=== PetkoKostov/ASP.NET/ASP_NBA_Project/App_Data/myDTD.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT MyProject (chap+)>
<!ELEMENT chap (team,history,achievments,arena,roster,free_agent*,star+,coach,add_info)>

<!ELEMENT team (#PCDATA)>
<!ATTLIST team wins CDATA  #REQUIRED>
<!-- CDATA = The value is character data -->
<!ATTLIST team loses CDATA #REQUIRED>
<!ATTLIST team playoffs  (Класира|Отпада)   #IMPLIED>
<!ATTLIST team in_division (Запад|Изток)   #REQUIRED>
<!ELEMENT history (#PCDATA)>

<!ELEMENT achievments (division_titles*,conference_titles*,league_titles*,notable_people*)>
<!-- Inline Group 1. "achievments" element can contain zero or more occurrences of parsed character data -->
<!ELEMENT division_titles (#PCDATA)>
<!ELEMENT conference_titles (#PCDATA)>
<!ELEMENT league_titles (#PCDATA)>
<!ELEMENT notable_people (#PCDATA)>


<!ELEMENT arena (#PCDATA)>
<!ATTLIST arena seats CDATA  #REQUIRED>

<!ELEMENT roster (player+)>
<!ELEMENT player (#PCDATA)>
<!ATTLIST player position (Плеймейкър|Гард|Леко-Крило|Тежко-Крило|Център)  #REQUIRED>

<!ELEMENT free_agent (fa_name,qual_offer,years_w_team)>
<!-- Inline Group 2-->
<!ELEMENT fa_name (#PCDATA)>
<!ELEMENT qual_offer (#PCDATA)>
<!ATTLIST qual_offer matched (Да|Не) "Не" >
<!ELEMENT years_w_team (#PCDATA)>

<!ELEMENT star (star_name,years_pro,salary,avg_pts)>
<!-- Inline Group 3-->
<!ELEMENT star_name (#PCDATA)>
<!ELEMENT years_pro (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT avg_pts (#PCDATA)>

<!ELEMENT coach (#PCDATA)>
<!ATTLIST coach salary CDATA #IMPLIED>
<!ATTLIST coach has_title (Да|Не) "Не" >
<!ATTLIST coach years_old CDATA #IMPLIED>

<!ELEMENT add_info (owner+,manager,site,colors,value,draft_position,dleague_affiliate*)>
<!-- Inline Group 4-->
<!ELEMENT owner (#PCDATA)>
<!ATTLIST owner billionaire (Да|Не) "Не" >
<!ELEMENT manager (#PCDATA)>
<!ELEMENT site (#PCDATA)>
<!ELEMENT colors (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT draft_position (#PCDATA)>
<!ELEMENT dleague_affiliate (#PCDATA) >

=== PetkoKostov/ASP.NET/ASP_NBA_Project/App_Data/myXML-5.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="xml-to-html-1.xslt" ?>

<!DOCTYPE MyProject SYSTEM "myDTD.dtd">
<!--Validated at: http://validator.w3.org/check -->
<MyProject>
  <chap>
    <team wins="25" loses="41" in_division="Изток" playoffs="Отпада">Детройт Пистонс</team>
    <history>Клубът първоначално е основан в Мичиган през 1941, но през 1948 се присъединява към НБА ситуирайки се в автомобилния град  Детройт.Въперки, че е относително малък франчайз, клубът се налага като един от силните отбори в НБА </history>
    <achievments>
      <division_titles>4</division_titles>
      <conference_titles>7</conference_titles>
      <league_titles>3</league_titles>
      <notable_people>
      </notable_people>
    </achievments>

    <arena seats="21454">Дъ Палас</arena>

    <roster>
      <player position="Плеймейкър">Родни Стъки</player>
      <player position="Гард">Брендън Найт</player>
      <player position="Леко-Крило">Грег Монро</player>
      <player position="Тежко-Крило">Тайшон Принс</player>
      <player position="Център">Бен Уолъс</player>
    </roster>

    <free_agent>
      <fa_name>Бен Уолъс</fa_name>
      <qual_offer>1000000</qual_offer>
      <years_w_team>8</years_w_team>
    </free_agent>

    <star>
      <star_name>Бен Уолъс</star_name>
      <years_pro>16</years_pro>
      <salary>2000000</salary>
      <avg_pts>7,2</avg_pts>
    </star>

    <coach salary="2000000" years_old="49">Джо Къстър</coach>

    <add_info>
      <owner billionaire="Да">Том Гор</owner>
      <manager>Джо Дюмарс</manager>
      <site>pistons.com</site>
      <colors>Бяло и сньо</colors>
      <value>332000000</value>
      <draft_position>8</draft_position>
      <dleague_affiliate>Мед Антс</dleague_affiliate>
    </add_info>

  </chap>

  <chap>
    <team wins="36" loses="30" in_division="Запад" playoffs="Отпада">Юта Джаз</team>
    <history>Франчайзът е основан през 1947 и е ситуиран в Ню Орлиънс.През 1979 се мести в Юта.Това не им носи късмет, тъй като в продължение на следващите 10 години не достигат плейофите.Обратно на тази  традиция в началото, на по-късен етап, отборът почти не пропуска плейофи (1984-2004) под ръководството на легендарния Джери Слоан, който е начело на отбора рекордните 23 години.  </history>
    <achievments>
      <division_titles>8</division_titles>
      <conference_titles>2</conference_titles>
      <league_titles>0</league_titles>
      <notable_people>
      </notable_people>
    </achievments>

    <arena seats="19911">Енерджи Солюшънс Арина</arena>

    <roster>
      <player position="Плеймейкър">Девин Харис</player>
      <player position="Гард">Гордън Хейуърд</player>
      <player position="Леко-Крило">Джош Хауърд</player>
      <player position="Тежко-Крило">Пол Милсап</player>
      <player position="Център">Ал Джеферсън</player>
    </roster>

    <free_agent>
      <fa_name>Морис Алмонд</fa_name>
      <qual_offer>1000000</qual_offer>
      <years_w_team>2</years_w_team>
    </free_agent>

    <star>
      <star_name>Ал Джеферсън</star_name>
      <years_pro>8</years_pro>
      <salary>14000000</salary>
      <avg_pts>15,9</avg_pts>
    </star>

    <coach salary="3000000" years_old="55">Тайлър Корбин</coach>

    <add_info>
      <owner>Гейл Милър</owner>
      <manager>Кевин О`Конър</manager>
      <site>utahjazz.com</site>
      <colors>Морско-снньо и жълто</colors>
      <value>335000000</value>
      <draft_position>3</draft_position>
      <dleague_affiliate>Стампдейт</dleague_affiliate>
    </add_info>

  </chap>
</MyProject>

=== PetkoKostov/ASP.NET/ASP_NBA_Project/App_Data/myXML-2.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="xml-to-html-1.xslt" ?>

<!DOCTYPE MyProject SYSTEM "myDTD.dtd">
<!--Validated at: http://validator.w3.org/check -->

<MyProject>
  <chap>
    <team wins="37" loses="29" in_division="Изток" playoffs="Класира">Орландо Меджик</team>
    <history>Основан и новопросъединен през 1989 година франчайз.Единствения спортен тим от голямата четворка на американските спортове, който играе в Орландо</history>
    <achievments>
      <division_titles>5</division_titles>
      <conference_titles>2</conference_titles>
      <league_titles>1</league_titles>
      <notable_people>
      </notable_people>
    </achievments>

    <arena seats="18846">Амуей Център</arena>

    <roster>
      <player position="Плеймейкър">Джамир Нелсън</player>
      <player position="Гард">Джей Джей Редик</player>
      <player position="Леко-Крило">Джейсън Ричардсън</player>
      <player position="Тежко-Крило">Глен Дейвис</player>
      <player position="Център">Дуайт Хауърд</player>
    </roster>

    <free_agent>
      <fa_name>Раян Андерсън</fa_name>
      <qual_offer>1000000</qual_offer>
      <years_w_team>4</years_w_team>
    </free_agent>

    <star>
      <star_name>Дуайт Хауърд</star_name>
      <years_pro>8</years_pro>
      <salary>13000000</salary>
      <avg_pts>18,2</avg_pts>
    </star>

    <coach salary="4000000" years_old="47">Стен Ван Гънди</coach>

    <add_info>
      <owner>RDV Sports, Inc.</owner>
      <manager>Отис Смит</manager>
      <site>orlandomagic.com</site>
      <colors>Синьо на черни райета</colors>
      <value>385000000</value>
      <draft_position>23</draft_position>
      <dleague_affiliate>Флорида Флейм</dleague_affiliate>
    </add_info>

  </chap>

  <chap>
    <team wins="39" loses="27" in_division="Изток" playoffs="Класира" >Бостън Селтикс</team>
    <history>Селтикс са най-успешния НБА отбор за всички времена.Броя на техните титли (17) не е надминат от никой отбор.Техен е и рекорда за най-много последователни титли-8 (1959–1966) </history>
    <achievments>
      <division_titles>20</division_titles>
      <conference_titles>21</conference_titles>
      <league_titles>17</league_titles>
      <notable_people>
      </notable_people>
    </achievments>

    <arena seats="18624">ТиДи Гардън</arena>

    <roster>
      <player position="Плеймейкър">Ражон Рондо</player>
      <player position="Гард">Рей Алън</player>
      <player position="Леко-Крило">Пол Пиърс</player>
      <player position="Тежко-Крило">Кевин Гарнет</player>
      <player position="Център">Джърмейн О`Нийл</player>
    </roster>

    <free_agent>
      <fa_name>Рей Алън</fa_name>
      <qual_offer>1000000</qual_offer>
      <years_w_team>4</years_w_team>
    </free_agent>

    <star>
      <star_name>Ражон Рондо</star_name>
      <years_pro>9</years_pro>
      <salary>10000000</salary>
      <avg_pts>10,7</avg_pts>
    </star>
    <star>
      <star_name>Рей Алън</star_name>
      <years_pro>16</years_pro>
      <salary>10000000</salary>
      <avg_pts>20,2</avg_pts>
    </star>
    <star>
      <star_name>Пол Пиърс</star_name>
      <years_pro>9</years_pro>
      <salary>15300000</salary>
      <avg_pts>22,2</avg_pts>
    </star>
    <star>
      <star_name>Кевин Гарнет</star_name>
      <years_pro>9</years_pro>
      <salary>21200000</salary>
      <avg_pts>19,6</avg_pts>
    </star>

    <coach salary="7000000" years_old="58">Док Ривърс</coach>

    <add_info>
      <owner>Boston Basketball Partners L.L.C.</owner>
      <manager>Дани Ейндж</manager>
      <site>celtics.com</site>
      <colors>Бяло и зелено</colors>
      <value>482000000</value>
      <draft_position>24</draft_position>
      <dleague_affiliate>Юта Флаш</dleague_affiliate>
    </add_info>

  </chap>
</MyProject>

=== PetkoKostov/ASP.NET/ASP_NBA_Project/App_Data/myXML-1.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" ?>

<!DOCTYPE MyProject SYSTEM "myDTD.dtd">
<!--Validated at: http://validator.w3.org/check   to validate <!DOCTYPE MyProject [ dtd ]>-->

<MyProject>
  <chap>
    <team wins="33" loses="33" in_division="Запад" playoffs="Отпада">Финикс Сънс</team>
    <history>
      Основан 1968 , състезаващ се в дивизия Пасифик и са единствения тим в дизивията
      който не е ситуиран в Калифорния
    </history>
    <achievments>
      <division_titles>6</division_titles>
      <conference_titles>2</conference_titles>
      <league_titles>0</league_titles>
      <notable_people>
      </notable_people>
    </achievments>

    <arena seats="19023">Еъруейс Център</arena>

    <roster>
      <player position="Плеймейкър">Стив Наш</player>
      <player position="Гард">Джерад Дъдли</player>
      <player position="Леко-Крило">Грант Хил</player>
      <player position="Тежко-Крило">Чанинг Фрай</player>
      <player position="Център">Марчин Гортат</player>
    </roster>

    <free_agent>
      <fa_name>Шанън Браун</fa_name>
      <qual_offer>2000000</qual_offer>
      <years_w_team>1</years_w_team>
    </free_agent>

    <free_agent>
      <fa_name >Робин Лопез</fa_name>
      <qual_offer matched="Да">4000000</qual_offer>
      <years_w_team>4</years_w_team>
    </free_agent>

    <star>
      <star_name>Стив Неш</star_name>
      <years_pro>14</years_pro>
      <salary>13000000</salary>
      <avg_pts>17,3</avg_pts>
    </star>
    <star>
      <star_name>Грант Хил</star_name>
      <years_pro>17</years_pro>
      <salary>6500000</salary>
      <avg_pts>13,7</avg_pts>
    </star>
    <coach salary="3000000" years_old="58">Алвин Джентри</coach>

    <add_info>
      <owner>Робърт Сарвър</owner>
      <manager>Ланс Бланкс</manager>
      <site>suns.com</site>
      <colors>Оранжево</colors>
      <value>283000000</value>
      <draft_position>13</draft_position>
      <dleague_affiliate>Бейкърсфилд Джем</dleague_affiliate>
    </add_info>

  </chap>

  <chap>
    <team wins="46" loses="20" in_division="Изток" playoffs="Класира" >Маями Хийт</team>
    <history>
      Член на югоизточната дивизия.Създаден по време на разрастването през 1988.Хийтс заедно
      с Оралндо Меджик са двата представители на Флорида
    </history>
    <achievments>
      <division_titles>8</division_titles>
      <conference_titles>2</conference_titles>
      <league_titles>1</league_titles>
      <notable_people>
      </notable_people>
    </achievments>

    <arena seats="19600">Америка Еърлайнс Арена</arena>

    <roster>
      <player position="Плеймейкър">Марио Чалмърс</player>
      <player position="Гард">Дуейн Уейдс</player>
      <player position="Леко-Крило">ЛеБрон Джеймс</player>
      <player position="Тежко-Крило">Крис Бош</player>
      <player position="Център">Джуел Антъни</player>
    </roster>

    <free_agent>
      <fa_name>Еди Къри</fa_name>
      <qual_offer>1000000</qual_offer>
      <years_w_team>1</years_w_team>
    </free_agent>

    <star>
      <star_name>ЛеБрон Джеймс</star_name>
      <years_pro>9</years_pro>
      <salary>14500000</salary>
      <avg_pts>28,0</avg_pts>
    </star>
    <star>
      <star_name>Дуейн Уейд</star_name>
      <years_pro>9</years_pro>
      <salary>14000000</salary>
      <avg_pts>25,9</avg_pts>
    </star>
    <star>
      <star_name>Крис Бош</star_name>
      <years_pro>9</years_pro>
      <salary>14500000</salary>
      <avg_pts>18,6</avg_pts>
    </star>

    <coach salary="3000000" years_old="42">Ерик Сплоестра </coach>

    <add_info>
      <owner billionaire="Да">Мики Арисон</owner>
      <manager>Пат Райли</manager>
      <site>heat.com</site>
      <colors>Тъмно-червено и черно</colors>
      <value>236000000</value>
      <draft_position>26</draft_position>
      <dleague_affiliate>Скай Форс</dleague_affiliate>
    </add_info>

  </chap>
</MyProject>

=== PetkoKostov/ASP.NET/ASP_NBA_Project/App_Data/myXML-7.xml
<?xml version="1.0"?>
<!DOCTYPE chap SYSTEM "D:\Projects\ASP\ASP_NBA_Project\ASP_NBA_Project\App_Data\myDTD.dtd">
<chap>
  <team wins="25" loses="41" playoffs="Отпада" in_division="Изток">Детройт Пистонс</team>
  <history>Клубът първоначално е основан в Мичиган през 1941, но през 1948 се присъединява към НБА ситуирайки се в автомобилния град  Детройт.Въперки, че е относително малък франчайз, клубът се налага като един от силните отбори в НБА.</history>
  <achievments>
    <division_titles>4</division_titles>
    <conference_titles>7</conference_titles>
    <league_titles>3</league_titles>
    <notable_people>
    </notable_people>
  </achievments>
  <arena seats="21454">Дъ Палас</arena>
  <roster>
    <player position="Плеймейкър">Родни Стъки</player>
    <player position="Гард">Брендън Найт</player>
    <player position="Леко-Крило">Грег Монро</player>
    <player position="Тежко-Крило">Тайшон Принс</player>
    <player position="Център">Бен Уолъс</player>
  </roster>
  <free_agent>
    <fa_name>Бен Уолъс</fa_name>
    <qual_offer matched="Не">1000000</qual_offer>
    <years_w_team>8</years_w_team>
  </free_agent>
  <star>
    <star_name>Бен Уолъс</star_name>
    <years_pro>16</years_pro>
    <salary>2000000</salary>
    <avg_pts>7,2</avg_pts>
  </star>
  <coach has_title="Да" salary="2000000" years_old="50">Джо Къстър</coach>
  <add_info>
    <owner billionaire="Не">Том Гор</owner>
    <manager>Джо Дюмарс</manager>
    <site>pistons.com</site>
    <colors>Бяло и сньо</colors>
    <value>332000000</value>
    <draft_position>8</draft_position>
    <dleague_affiliate>Мед Антс</dleague_affiliate>
  </add_info>
</chap>

=== PetkoKostov/ASP.NET/ASP_NBA_Project/App_Data/myXML-3.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="xml-to-html-1.xslt" ?>

<!DOCTYPE MyProject SYSTEM "myDTD.dtd">
<!--Validated at: http://validator.w3.org/check -->

<MyProject>
  <chap>
    <team wins="36" loses="30" in_division="Запад" playoffs="Класира">Далас Маверикс</team>
    <history>Отбора на Маверикс е настоящия шампион на НБА.Имат може би най-известния собственик на спортен отбор в САЩ - Марк Кюбан.Известен със своята ексцентричност, той е човекът донесъл първа титла на отбора от неговото създаване през 1980.</history>
    <achievments>
      <division_titles>3</division_titles>
      <conference_titles>2</conference_titles>
      <league_titles>1</league_titles>
      <notable_people>Марк Кюбан</notable_people>
    </achievments>

    <arena seats="19200">Американ Еърлайнс Център</arena>

    <roster>
      <player position="Плеймейкър">Джейсън Кид</player>
      <player position="Гард">Родриг Бобуа</player>
      <player position="Леко-Крило">Шон Мериън</player>
      <player position="Тежко-Крило">Дирк Новитзки</player>
      <player position="Център">Брендън Хейуърд</player>
    </roster>

    <free_agent>
      <fa_name>Джейсън Кид</fa_name>
      <qual_offer>1000000</qual_offer>
      <years_w_team>3</years_w_team>
    </free_agent>

    <star>
      <star_name>Дирк Новитзки</star_name>
      <years_pro>14</years_pro>
      <salary>17000000</salary>
      <avg_pts>23</avg_pts>
    </star>

    <star>
      <star_name>Джейсън Кид</star_name>
      <years_pro>18</years_pro>
      <salary>8800000</salary>
      <avg_pts>13,2</avg_pts>
    </star>

    <coach has_title="Да" years_old="52" salary="4000000">Рик Карслайл</coach>

    <add_info>
      <owner billionaire="Да">Марк Кюбан</owner>
      <manager>Дони Нелсън</manager>
      <site>mavs.com</site>
      <colors>Черно и бяло</colors>
      <value>497000000</value>
      <draft_position>26</draft_position>
      <dleague_affiliate>Форд Флайърс</dleague_affiliate>
    </add_info>

  </chap>

  <chap>
    <team wins="23" loses="43" in_division="Изток" playoffs="Отпада" >Торонто Раптърс</team>
    <history>Раптърс са единствения кандаски тим състезаващ се в НБА.Създаден през 1995 година заедно с отбора на Ванкувър Гризлис(по-късно преместил се в Мемфис) като част от експанзията на асоциацията в посока Канада</history>
    <achievments>
      <division_titles>1</division_titles>
      <conference_titles>0</conference_titles>
      <league_titles>0</league_titles>
      <notable_people>
      </notable_people>
    </achievments>

    <arena seats="22911 ">Скай Доум</arena>

    <roster>
      <player position="Плеймейкър">Хосе Калдерон</player>
      <player position="Гард">Демар Дерожан</player>
      <player position="Леко-Крило">Джеймс Джонсън</player>
      <player position="Тежко-Крило">Андреа Барняни</player>
      <player position="Център">Аарон Грей</player>
    </roster>

    <free_agent>
      <fa_name>Джерад Бейлис</fa_name>
      <qual_offer>1000000</qual_offer>
      <years_w_team>2</years_w_team>
    </free_agent>

    <star>
      <star_name>Андреа Барняни</star_name>
      <years_pro>6</years_pro>
      <salary>9000000</salary>
      <avg_pts>15,1</avg_pts>
    </star>

    <coach salary="3000000" years_old="46">Дуейн Кейси</coach>

    <add_info>
      <owner>Maple Leaf Sports and Entertainment</owner>
      <manager>Брайън Коланджело</manager>
      <site>raptors.com</site>
      <colors>Червено и черно</colors>
      <value>482000000</value>
      <draft_position>5</draft_position>
    </add_info>

  </chap>
</MyProject>

=== PetkoKostov/ASP.NET/ASP_NBA_Project/App_Data/myXML-8.xml
<?xml version="1.0"?>
<!DOCTYPE chap SYSTEM "D:\Projects\ASP\ASP_NBA_Project\ASP_NBA_Project\App_Data\myDTD.dtd">
<chap>
  <team wins="46" loses="20" playoffs="Класира" in_division="Изток">Маями Хийт</team>
  <history>Член на югоизточната дивизия.Създаден по време на разрастването през 1988.Хийтс заедно с Оралндо Меджик са двата представители на Флорида.</history>
  <achievments>
    <division_titles>8</division_titles>
    <conference_titles>2</conference_titles>
    <league_titles>1</league_titles>
    <notable_people>
    </notable_people>
  </achievments>
  <arena seats="19600">Америка Еърлайнс Арена</arena>
  <roster>
    <player position="Плеймейкър">Марио Чалмърс</player>
    <player position="Гард">Дуейн Уейдс</player>
    <player position="Леко-Крило">ЛеБрон Джеймс</player>
    <player position="Тежко-Крило">Крис Бош</player>
    <player position="Център">Джуел Антъни</player>
  </roster>
  <free_agent>
    <fa_name>Еди Къри</fa_name>
    <qual_offer matched="Не">1000000</qual_offer>
    <years_w_team>1</years_w_team>
  </free_agent>
  <star>
    <star_name>ЛеБрон Джеймс</star_name>
    <years_pro>9</years_pro>
    <salary>14500000</salary>
    <avg_pts>28,0</avg_pts>
  </star>
  <coach has_title="Да" salary="3000000" years_old="42">Ерик Сплоестра</coach>
  <add_info>
    <owner billionaire="Не">Мики Арисон&lt;</owner>
    <manager>Пат Райли</manager>
    <site>heat.com</site>
    <colors>Тъмно-червено и черно</colors>
    <value>236000000</value>
    <draft_position>26</draft_position>
    <dleague_affiliate>Скай Форс</dleague_affiliate>
  </add_info>
</chap>

=== PetkoKostov/ASP.NET/ASP_NBA_Project/App_Data/myXML-4.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="xml-to-html-1.xslt" ?>

<!DOCTYPE MyProject SYSTEM "myDTD.dtd">
<!--Validated at: http://validator.w3.org/check -->

<MyProject>
  <chap>
    <team wins="41" loses="25" in_division="Запад" playoffs="Класира">Лос Анджелис Лейкърс</team>
    <history>Лейкърс са един от двата НБА тима които играят в Лос Анджелис.Заедно с отбора на Бостън Селктикс оформят най-голямото съперничество в асоцияцията през годините, още повечте, че двата отбора са и най-успешните в историята.Отборът е основан през 1947 под името Минеаполис Лейкърс, но преместен 13 години по-късно в Града на ангелите. </history>
    <achievments>
      <division_titles>22</division_titles>
      <conference_titles>31</conference_titles>
      <league_titles>17</league_titles>
      <notable_people>Фил Джаксън</notable_people>
    </achievments>

    <arena seats="18997">Стейпълс Център</arena>

    <roster>
      <player position="Плеймейкър">Дерек Фишър</player>
      <player position="Гард">Кобе Брайънт</player>
      <player position="Леко-Крило">Рон Артеср</player>
      <player position="Тежко-Крило">Поу Гасол</player>
      <player position="Център">Андрю Байнъм</player>
    </roster>

    <free_agent>
      <fa_name>Мат Барнс</fa_name>
      <qual_offer>1000000</qual_offer>
      <years_w_team>2</years_w_team>
    </free_agent>

    <free_agent>
      <fa_name>Трой Мърфи</fa_name>
      <qual_offer>1000000</qual_offer>
      <years_w_team>1</years_w_team>
    </free_agent>

    <star>
      <star_name>Кобе Брайънт</star_name>
      <years_pro>16</years_pro>
      <salary>23000000</salary>
      <avg_pts>25,4</avg_pts>
    </star>

    <star>
      <star_name>Поу Гасол</star_name>
      <years_pro>11</years_pro>
      <salary>18700000</salary>
      <avg_pts>17,9</avg_pts>
    </star>

    <coach salary="4500000" years_old="52">Майк Браун</coach>

    <add_info>
      <owner billionaire="Да">Джери Бъс</owner>
      <manager>Митч Къпчак</manager>
      <site>lakers.com</site>
      <colors>Златно-жълто и лилаво</colors>
      <value>900000000</value>
      <draft_position>27</draft_position>
      <dleague_affiliate>Форт Флайърс</dleague_affiliate>
    </add_info>

  </chap>

  <chap>
    <team wins="36" loses="30" in_division="Изток" playoffs="Класира" >Ню-Йорк Никс</team>
    <history>Създаден през 1946 отботра на Никс е един от създателите на БАА по-късно трансформирана в НБА.Отборът играе мачовете си в Медисън Скуеър Гардън, считана от мнозина за меката на баскетбола.</history>
    <achievments>
      <division_titles>4</division_titles>
      <conference_titles>8</conference_titles>
      <league_titles>2</league_titles>
      <notable_people>
      </notable_people>
    </achievments>

    <arena seats="19763">Медисън Скуеър Гардън</arena>

    <roster>
      <player position="Плеймейкър">Ландри Фийлс</player>
      <player position="Гард">Иън Шъмпърт</player>
      <player position="Леко-Крило">Кармело Антъни</player>
      <player position="Тежко-Крило">Амаре Сртудамеиър</player>
      <player position="Център">Тайсън Чандлър</player>
    </roster>

    <free_agent>
      <fa_name>Майк Биби</fa_name>
      <qual_offer>1000000</qual_offer>
      <years_w_team>1</years_w_team>
    </free_agent>

    <star>
      <star_name>Кармело Антъни</star_name>
      <years_pro>9</years_pro>
      <salary>18500000</salary>
      <avg_pts>24,8</avg_pts>
    </star>

    <star>
      <star_name>Амаре Сртудамеиър</star_name>
      <years_pro>10</years_pro>
      <salary>18200000</salary>
      <avg_pts>21,9</avg_pts>
    </star>

    <coach salary="6000000" years_old="55">Майк Д`Антъни</coach>

    <add_info>
      <owner billionaire="Да">Джеймс Долън</owner>
      <owner>Madison Square Garden, Inc.</owner>
      <manager>Глен Грънуалд</manager>
      <site>knicks.com</site>
      <colors>Бяло, оранжево и синьо</colors>
      <value>780000000</value>
      <draft_position>17</draft_position>
      <dleague_affiliate>Пейтриътс</dleague_affiliate>
    </add_info>

  </chap>
</MyProject>
